name: CI

on:
  push:
    branches: ["master"]

jobs:
  build:
    runs-on: "ubuntu-20.04"

    steps:
      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build
        uses: docker/build-push-action@v2
        with:
          tags: "boord/epl:latest"
          platforms: linux/amd64,linux/arm64
          push: true
          cache-from: type=registry,ref=primeimages/primes:latest
          cache-to: type=inline
